### PR TITLE
refactor: Upgrade kclvm/cmd clap version to 4.x

### LINKED ISSUE #333: [Enhancement] KCLVM CLI clap deps is too low and need to upgrade the clap version.
## Enhancement

KCLVM CLI clap deps is too low, upgrade the version and Refactoring code in the way recommended by clap. Ref: clap-rs/clap#2835

### PR DESCRIPTION
**Pull request by niconical**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y

fix #333

#### 2. What is the scope of this PR:

- kclvm/Cargo.lock
- kclvm/cmd/Cargo.toml
- kclvm/cmd/src/fmt.rs
- kclvm/cmd/src/lib.rs
- kclvm/cmd/src/lint.rs
- kclvm/cmd/src/settings.rs
- kclvm/cmd/src/util.rs
- kclvm/cmd/src/vet.rs

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

Summary of changes:

- Use `Arg.num_args`
   - [Supersedes](https://github.com/clap-rs/clap/issues/2688) `multiple_values` and `takes_value`
- Use `ArgMatches.get_one` and `ArgMatches.get_many` in place of `ArgMatches.value_of*` and `ArgMatches.values_of*`
- Replace `occurrences_of` with `ArgAction::Count` and `get_count`  for flag counting
- Replace `occurrences_of`with `get_flag` for flags whether

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [ ] N
- [x] Y 

This PR updates the dependency of clap from 3.x to 4.x in [kclvm/cmd](https://github.com/KusionStack/KCLVM/tree/main/kclvm), resulting in significant changes to the CLI interface style, such as [color support](https://stackoverflow.com/questions/74068168/clap-rs-not-printing-colors-during-help).

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [x] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

If there are any defects in this PR, please contact me in time.

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Peefy** [comment]
> /assign @Peefy

Thank you for your contribution. I have allowed testing and you can execute `make fmt` to format the submitted code.

**Comment by niconical** [comment]
I have discovered some issues while executing the [example](https://github.com/KusionStack/kcl-lang.io/tree/main/examples).

**Comment by Peefy** [comment]
> I have discovered some issues while executing the [example](https://github.com/KusionStack/kcl-lang.io/tree/main/examples)，I will solve them.

OK, go ahead!

**Comment by Peefy** [comment]
@niconical CI failed, corresponding test cases need to be modified.

**Comment by niconical** [comment]
> @niconical CI failed, corresponding test cases need to be modified.

I've been struggling with this problem lately, when I execute [abstraction](https://github.com/KusionStack/kcl-lang.io/tree/main/examples/abstraction) I get the following error:

```shell
Testing abstraction ...
make docker
make[1]: Entering directory '/home/ch/kcl-lang.io/examples/abstraction'
kcl main.k docker_compose_render.k
While deleting: %kclvm_value_ref_t** %$backtrack_cache
Use still stuck around after Def is destroyed:  %"$backtrack_cache6" = load %kclvm_value_ref_t*, %kclvm_value_ref_t** %"$backtrack_cache", align 8
kclvm_cli: /home/ch/llvm-12.0.0.src/lib/IR/Value.cpp:100: llvm::Value::~Value(): Assertion `materialized_use_empty() && "Uses remain when a value is destroyed!"' failed.
Aborted (core dumped)
make[1]: *** [Makefile:2: docker] Error 134
make[1]: Leaving directory '/home/ch/kcl-lang.io/examples/abstraction'
make: *** [Makefile:8: test] Error 2
Test FAILED - abstraction
```
I don't know why my changes affect the `~Value()` method in LLVM.

**Comment by Peefy** [comment]
> > @niconical CI failed, corresponding test cases need to be modified.
> 
> I've been struggling with this problem lately, when I execute [abstraction](https://github.com/KusionStack/kcl-lang.io/tree/main/examples/abstraction) I get the following error:
> 
> ```shell
> Testing abstraction ...
> make docker
> make[1]: Entering directory '/home/ch/kcl-lang.io/examples/abstraction'
> kcl main.k docker_compose_render.k
> While deleting: %kclvm_value_ref_t** %$backtrack_cache
> Use still stuck around after Def is destroyed:  %"$backtrack_cache6" = load %kclvm_value_ref_t*, %kclvm_value_ref_t** %"$backtrack_cache", align 8
> kclvm_cli: /home/ch/llvm-12.0.0.src/lib/IR/Value.cpp:100: llvm::Value::~Value(): Assertion `materialized_use_empty() && "Uses remain when a value is destroyed!"' failed.
> Aborted (core dumped)
> make[1]: *** [Makefile:2: docker] Error 134
> make[1]: Leaving directory '/home/ch/kcl-lang.io/examples/abstraction'
> make: *** [Makefile:8: test] Error 2
> Test FAILED - abstraction
> ```
> 
> I have no idea why my changes affect the `~Value()` method in LLVM.



> > @niconical CI failed, corresponding test cases need to be modified.
> 
> I've been struggling with this problem lately, when I execute [abstraction](https://github.com/KusionStack/kcl-lang.io/tree/main/examples/abstraction) I get the following error:
> 
> ```shell
> Testing abstraction ...
> make docker
> make[1]: Entering directory '/home/ch/kcl-lang.io/examples/abstraction'
> kcl main.k docker_compose_render.k
> While deleting: %kclvm_value_ref_t** %$backtrack_cache
> Use still stuck around after Def is destroyed:  %"$backtrack_cache6" = load %kclvm_value_ref_t*, %kclvm_value_ref_t** %"$backtrack_cache", align 8
> kclvm_cli: /home/ch/llvm-12.0.0.src/lib/IR/Value.cpp:100: llvm::Value::~Value(): Assertion `materialized_use_empty() && "Uses remain when a value is destroyed!"' failed.
> Aborted (core dumped)
> make[1]: *** [Makefile:2: docker] Error 134
> make[1]: Leaving directory '/home/ch/kcl-lang.io/examples/abstraction'
> make: *** [Makefile:8: test] Error 2
> Test FAILED - abstraction
> ```
> 
> I have no idea why my changes affect the `~Value()` method in LLVM.

You can open another issue to discuss this issue to avoid information loss. I estimate it is a problem with your LLVM build parameters, https://github.com/KusionStack/kcl/blob/main/scripts/build-llvm/build.sh

**Comment by niconical** [comment]
I noticed the bug reported in CI
```shell
FAILED test_grammar.py::test_grammar[/home/ch/kcl/test/grammar/builtins/json/output_2] - ruamel.yaml.parser.ParserError: expected '<document start>', but found ('<scalar>',)
```
But when I use the latest kcl release version to execute `cd kcl/kclvm/tests/integration/grammar && kclvm -m pytest -v -n 5`, I still encounter the same problem. This seems to be a problem with the yaml parser?

Here are some environment parameters:
1. The version of the kcl release I used
```shell
$ kclvm_cli version
Version: 0.5.0-alpha.1-eb2f4d1aabc2a287c298bc35c5fcfec1
Platform: x86_64-unknown-linux-gnu
GitCommit: VERGEN_IDEMPOTENT_OUTPUT
```
3. My OS environment
```shell
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by Peefy** [comment]
> I noticed a [FAILED](https://github.com/KusionStack/kcl/actions/runs/5132507598/jobs/9233901575) reported in CI
> 
> ```shell
> FAILED test_grammar.py::test_grammar[/home/ch/kcl/test/grammar/builtins/json/output_2] - ruamel.yaml.parser.ParserError: expected '<document start>', but found ('<scalar>',)
> ```
> 
> But when I use the [latest kcl release version](https://github.com/KusionStack/kcl/releases/tag/v0.5.0-alpha.1) to execute `cd kcl/kclvm/tests/integration/grammar && kclvm -m pytest -v -n 5`, I still encounter the same problem.
> 
> Here are some environment parameters:
> 
> 1. The version of the kcl release I used
> 
> ```shell
> $ kclvm_cli version
> Version: 0.5.0-alpha.1-eb2f4d1aabc2a287c298bc35c5fcfec1
> Platform: x86_64-unknown-linux-gnu
> GitCommit: VERGEN_IDEMPOTENT_OUTPUT
> ```
> 
> 3. My OS environment
> 
> ```shell
> $ cat /etc/os-release
> PRETTY_NAME="Ubuntu 22.04.2 LTS"
> NAME="Ubuntu"
> VERSION_ID="22.04"
> VERSION="22.04.2 LTS (Jammy Jellyfish)"
> VERSION_CODENAME=jammy
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> UBUNTU_CODENAME=jammy
> ```



> I noticed a [FAILED](https://github.com/KusionStack/kcl/actions/runs/5132507598/jobs/9233901575) reported in CI
> 
> ```shell
> FAILED test_grammar.py::test_grammar[/home/ch/kcl/test/grammar/builtins/json/output_2] - ruamel.yaml.parser.ParserError: expected '<document start>', but found ('<scalar>',)
> ```
> 
> But when I use the [latest kcl release version](https://github.com/KusionStack/kcl/releases/tag/v0.5.0-alpha.1) to execute `cd kcl/kclvm/tests/integration/grammar && kclvm -m pytest -v -n 5`, I still encounter the same problem.
> 
> Here are some environment parameters:
> 
> 1. The version of the kcl release I used
> 
> ```shell
> $ kclvm_cli version
> Version: 0.5.0-alpha.1-eb2f4d1aabc2a287c298bc35c5fcfec1
> Platform: x86_64-unknown-linux-gnu
> GitCommit: VERGEN_IDEMPOTENT_OUTPUT
> ```
> 
> 3. My OS environment
> 
> ```shell
> $ cat /etc/os-release
> PRETTY_NAME="Ubuntu 22.04.2 LTS"
> NAME="Ubuntu"
> VERSION_ID="22.04"
> VERSION="22.04.2 LTS (Jammy Jellyfish)"
> VERSION_CODENAME=jammy
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> UBUNTU_CODENAME=jammy
> ```

Thank you for your feedback. After investigation, it has been found that there has been a change in the logic of the upstream YAML library. I have temporarily fixed the version of `ruamel.yaml` in CI to `0.16.12` to bypass it. I have reviewed your code and I will merge it. ❤️

**Review by Peefy — APPROVED** [review]
LGTM

**Pull request merged**
